const { withProjectBuildGradle, withAppBuildGradle } = require("@expo/config-plugins");

// Pinned to the last 3.x release: GPP 4.x requires Gradle 9.1+, but Expo/RN
// pins this project to Gradle 8.14.3 (see android/gradle/wrapper/
// gradle-wrapper.properties, regenerated by prebuild) - bumping Gradle just
// for this plugin isn't worth the risk to RN's carefully matched
// AGP/Kotlin/NDK version set. Revisit once Expo/RN moves to Gradle 9.
const GPP_VERSION = "3.13.0";

// Wires up Gradle Play Publisher (github.com/Triple-T/gradle-play-publisher)
// on every `expo prebuild`, so `./gradlew publishBundle` can upload a
// release .aab straight to the Play Console. Reads the service account
// key path and target track from environment variables at Gradle build
// time - never baked into the repo. Mirrors withAndroidSigning.js's
// approach: this whole file only edits the generated Gradle files.
function withPlayPublisher(config) {
  config = withProjectBuildGradle(config, (config) => {
    const contents = config.modResults.contents;

    if (contents.includes("com.github.triplet.gradle:play-publisher")) {
      return config;
    }

    config.modResults.contents = contents.replace(
      /classpath\('com\.facebook\.react:react-native-gradle-plugin'\)/,
      `classpath('com.facebook.react:react-native-gradle-plugin')\n    classpath('com.github.triplet.gradle:play-publisher:${GPP_VERSION}')`,
    );

    return config;
  });

  config = withAppBuildGradle(config, (config) => {
    const contents = config.modResults.contents;

    if (contents.includes("com.github.triplet.play")) {
      return config;
    }

    const playBlock = `
play {
    def credentialsPath = System.getenv("PLAY_SERVICE_ACCOUNT_JSON")
    if (credentialsPath) {
        serviceAccountCredentials.set(file(credentialsPath))
    }
    track.set(System.getenv("PLAY_TRACK") ?: "internal")
    releaseStatus.set(com.github.triplet.gradle.androidpublisher.ReleaseStatus.COMPLETED)
    defaultToAppBundles.set(true)
}
`;

    config.modResults.contents = contents.replace(
      /apply plugin: "com\.facebook\.react"/,
      `apply plugin: "com.facebook.react"\napply plugin: "com.github.triplet.play"\n${playBlock}`,
    );

    return config;
  });

  return config;
}

module.exports = withPlayPublisher;
